### ISSUE TITLE
serialized_options

### ISSUE THREAD

**Issue by Marvll** [zackmark29/CDM-Device-Checker#3]
CDM-Device-Checker-master\wv_proto\wv_proto2_pb2.py", line 17, in <module>
    DESCRIPTOR = _descriptor.FileDescriptor(
TypeError: __init__() got an unexpected keyword argument 'serialized_options'

**Comment by zackmark29** [comment]
Ahm looks like you are checking invalid client_id_blob.
Could you post the challenge here?

**Comment by Marvll** [comment]
> Already installed it
client_id_blob [https://github.com/weapon121/L1-Give-Away](url)

**Comment by zackmark29** [comment]
> https://github.com/weapon121/L1-Give-Away

Can't reproduce that without other information. (Like the file or challenge you are trying to check)
The error you are getting is from protobuf which is auto generated script only.
or maybe you installed that package in your other python version.
