### ISSUE TITLE
Make "colored_print" optional

### ISSUE THREAD

**Issue by Vangelis66** [zackmark29/CDM-Device-Checker#5]
Hi :smile: ; first, many thanks for authoring and maintaining this nice script :+1: !

Now, in versions **1.0.5**+, 

> - colored output for device info and logger

[has been implemented](https://github.com/zackmark29/CDM-Device-Checker/commit/07cf2236a), via `colored_print`, as a cosmetic/**visual enhancement**; however: 
1. Is this feature limited by Windows OS version?
2. Is this feature limited by CPython version?

At the time of this writing, the scripts are **py3.6+** compatible, this means minimum system requirement is Windows Vista SP2 32/64-bit, with either py**3.6/3.7**; and Python EoLs Windows 7 SP1 with py**3.8** ...

When the `check.py` script is run on **Windows 7 SP1 64-bit/CPython 3.7.9 32-bit**, this is how the Command Prompt Window looks like: 

![color_printing](https://user-images.githubusercontent.com/9669492/151384862-86d1526e-099a-428d-84da-b32c8f121d24.jpg)

The case is the same when **Vista SP2 32-bit/CPython 3.7.9 32-bit** (older but fully functional laptop) is being used... 

**Google** have recently given **Win7** another year of grace period (Jan 23rd 2023), this includes their **WidevineCDM** - now on version 4.10.**2449**.0, so I guess this **still popular** OS will stick around for a while longer... :wink: 

Can the `colored_print` code be made **optional** in environments where it doesn't work as intended? 
Ideally, a "dynamic" solution would be preferred (make the scripts detect support for it), barring that a **user-configurable setting** inside `config.py`, if possible... 

Thanks for your time and attention :smiley_cat:

**Comment by Vangelis66** [comment]
... A workaround to experience **colored output** where the **native** Windows `cmd.exe` doesn't support it is to use a **console emulator**, e.g. **cmder**: 

![cmder](https://user-images.githubusercontent.com/9669492/151463822-21bcda1f-92e7-40e4-9846-5be9610ebb4d.jpg)

(this is from my older **WinVista SP2 x86** laptop; the `Cobalt2` **color scheme** has been selected :wink:); 
more info on cmder: 
```
https://cmder.net
https://github.com/cmderdev/cmder
```

**Comment by zackmark29** [comment]
> ... A workaround to experience **colored output** where the **native** Windows `cmd.exe` doesn't support it is to use a **console emulator**, e.g. **cmder**:
> 
> ![cmder](https://user-images.githubusercontent.com/9669492/151463822-21bcda1f-92e7-40e4-9846-5be9610ebb4d.jpg)
> 
> (this is from my older **WinVista SP2 x86** laptop; the `Cobalt2` **color scheme** has been selected 😉); more info on cmder:
> 
> ```
> https://cmder.net
> https://github.com/cmderdev/cmder
> ```

Good solution. I also added other tool so you can just run directly the cmd. Just read the changelogs

**Comment by Vangelis66** [comment]
Many thanks for the swift fixes! :+1: :heart: 

> Just read the changelogs

=>

>> - Colored is now optional (see config.py)

The default is now **OFF**:

https://github.com/zackmark29/CDM-Device-Checker/blob/da44f231a370cd0a1e962a8a1e8bad053ad58783/config.py#L15

To enable, just replace `False` with `True` (emphasis on the capital **T**) and save this `config.py` edit!

Best regards
